### ISSUE TITLE
Official way to create an aux collection programmatically

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-documentdb-changefeedprocessor-dotnet#142]
Per #94 it seems that there's no need to set an explicit TTL on an auxiliary collection, however I have not seen a canonical set of rules for what the minimal requirements are for an `-aux` collection.

Can someone officially confirm that this is appropriate code to create the `aux` collection please?

    var def = new DocumentCollection(Id = collName);
    var dbUri = UriFactory.CreateDatabaseUri(dbName);
    var opts = new RequestOptions(OfferThroughput = 400);
    await client.CreateDocumentCollectionIfNotExistsAsync(dbUri, def, opts);

- can it be confirmed that no `IndexingPolicy` is required [and hence leaving it as the default `None` is sufficient] ?

**Comment by bartelink** [comment]
About to close on basis that 
a) comments in linked v3 SDK issue 491 confirm everything should have a PK and `id` is the correct and valid one for a CFP aux collection
b) `IndexingPolicy.Automatic` can be `false`
c) `IndexingPolicy.IndexingMode` can be `IndexingMode.None`
@ealsur can I prey on you to confirm the latter two prior to my closing the issue please? ([code](https://github.com/jet/equinox/blob/3f63a856de482afe4cd6ad15707c9b4c2c4f5ad6/src/Equinox.Cosmos/Cosmos.fs#L527)

**Comment by ealsur** [comment]
I would ask @mkolt to double confirm on the IndexingPolicy, but as far as I know, the only requisite is the /id PK.

**Comment by bartelink** [comment]
@ealsur prompted by [this SO answer you linked to recently](https://stackoverflow.com/a/58721386/11635) I'm having doubts about whether it's safe for me to assume that having indexing configured as:
```json
{
    "indexingMode": "none",
    "automatic": false,
    "includedPaths": [],
    "excludedPaths": []
}
```
is definitely supported for the V2 and/or later CFP impls

for reference: [code that generated the collection and its indexing policy](https://github.com/jet/equinox/blob/3f63a856de482afe4cd6ad15707c9b4c2c4f5ad6/src/Equinox.Cosmos/Cosmos.fs#L527)

**Comment by ealsur** [comment]
The indexing policy you are describing is not indexing anything since the IndexingMode is None (https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy#indexing-mode). 

The only requirement for the partitioned lease collection is to have `/id` as partition key, if it doesn't have it, it will error out on Host initialization stating this.

Why are you customizing the Indexing Policy of a collection your user code is not taking any actions against? Normally one customizes the Policy based on the queries or operations that are done there from one's applications, but since the lease collection is used exclusively by CFP, what is the base upon which you are customizing or changing it?

**Comment by bartelink** [comment]
Thanks for the clear answer.

My intent is to deliberately configure the policy I wish to have in place for both CFP and ones I directly manage. If no indexes are of any value, I don't want to pay RUs or latency for them. I don't want to be taking screenshots of how you click to make a CFP container and am unaware of any recommended automated way to generate them.

(slightly longer and more accurate answer: I ended up explicitly wiring it this way as some systems used to sneak stuff into the leases container, and did require indexes for that purpose (no, it didn't end well))
